### ISSUE TITLE
set Report’s rounding_digits in compare

### ISSUE THREAD

**Issue by PaulLerner** [AmenRa/ranx#11]
Hi,

`compare` does not have a `rounding_digits` argument and thus always uses the default from `Report` (which is 4). Why is that?

Also, would you like to add an option in Report to print results as percentages rather than ratios ?

**Comment by AmenRa** [comment]
Hi Paul,

I have chosen the number of digits based on the max number of digits I found in IR / SecSys papers for reporting performance scores. However, I was planning on adding an argument as you suggested, but it seems I forgot about it. My bad.

Regarding using percentages instead of ratios, do you mean 0.432 -> 43.2?

Best,

Elias

**Comment by PaulLerner** [comment]
Thanks for your (very) quick answer!
Yes, I mean 0.432 -> 43.2 (optionally).

**Comment by AmenRa** [comment]
In the meantime, mind that you can change the Report parameter before printing:
`report.rounding_digits = 3`

**Comment by AmenRa** [comment]
Added in `0.1.11`. Please, take a look at the [changelog](https://github.com/AmenRa/ranx/blob/master/changelog.md) I added as some changes could break your code.

Closing.
