### ISSUE TITLE
[Question] About the correction among multiple hypotheses

### ISSUE THREAD

**Issue by striver314** [AmenRa/ranx#61]
I came across a point in the [Fuhr](https://www.sigir.org/wp-content/uploads/2018/01/p032.pdf) article where it talks about the need for additional correction for multiple hypotheses test (e.g., Bonferroni correction). Looking at the `paired_student_t_test` function code, it seems like the correction procedure is not taken into account.

Am I on the right track with this? If the current version does indeed consider this, could you guide me on how to verify it?

**Comment by AmenRa** [comment]
Hi and sorry for the delay.

You can apply Bonferroni correction by changing the `max_p` parameter of the `compare` function (Maximum p-value to consider an increment as statistically significant. Defaults to 0.01.).

Otherwise, you can use the [Tukey's HSD Test](https://www.itl.nist.gov/div898/handbook/prc/section4/prc471.htm), as suggested by Fuhr in the same article, by passing `Tukey` as `stat_test` parameter of `compare`.

Closing.
